

<?php 
//Formlaire d'edition
if(!empty($user)){
   
    foreach($user as $user): ?>
    <div class="w-50 p-3 mx-auto">
        <form action="update" method="POST">
            <h1>Edition de la catégorie - ID: <?= $user->getId() ?></h1>
            <input type="hidden" name="id" value="<?= $user->getId() ?>" id="id">
            <div class="form-group">
                <label for="name">Nom du User</label>
                <input type="text" name="name" id="name" value="<?= $user->getName() ?>" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="name">Password</label>
                <input type="password" name="pwd" id="pwd" value="" class="form-control" minlength="8" placeholder="Redéfinir password" required>
            </div>
            <br>
            <div class="text-center">
                <input type="submit" value="Update user" class="btn btn-primary">
            </div>
        </form>
    </div>
        
<?php
    endforeach ;
}
else{
//Formulaire d'ajout
?>
    <div class="w-50 p-3 mx-auto">
        <form action="insert" method="POST">
            <h1>Nouveau user</h1>
            <div class="form-group">
                <label for="name">Nom du User</label>
                <input type="text" name="name" id="name" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="name">Password</label>
                <input type="password" name="pwd" id="pwd" class="form-control" minlength="8" required>
            </div>
            <br>
            <div class="text-center">
                <input type="submit" value="Ajouter un user" class="btn btn-primary">
            </div>
        </form>
    </div>
<?php
}
?>