

<?php 
if(!empty($article)){
    foreach($article as $article): ?>
    <div class="w-50 p-3 mx-auto">
        <form action="update" method="POST">
            <h1>Edition de l'article - ID: <?= $article->getId() ?></h1>
            <input type="hidden" name="id" value="<?= $article->getId() ?>" id="id">
            <div class="form-group">
                <label for="name">Nom de l'article</label>
                <input type="text" name="name" id="name" value="<?= $article->getName() ?>" class="form-control" required>
            </div>
            <div class="form-group" >
            <br>
            <select  class="form-select" aria-label="select category" name="categoryId" id="categoryId" required>
                    <option value="<?=$article->getCategoryId()?>"><?=$article->getCategoryId()?></option>
                    <?php foreach($categories as $category):?>
                        <option value="<?= $category->getId()?>"><?=$category->getName()?></option>
                    <?php endforeach ?>
                    
                </select>
            </div>
            <br>
            <div class="form-group">
                <label for="title">Titre de l'article</label>
                <input type="text" name="title" id="title" value="<?= $article->getTitle() ?>" class="form-control" required>
            </div>
            <div class="form-group" >
                <label for="content">Contenu de l'article</label>
                <textarea id="content" name="content" rows="3" class="form-control"><?= $article->getContent() ?></textarea>
            </div>
            <br>
            <div class="text-center">
                <input type="submit" value="Update article" class="btn btn-primary">
            </div>
        </form>
    </div>
    
<?php
    endforeach ;
}
else{
?>
    <div class="w-50 p-3 mx-auto">
        <form action="insert" method="POST">
            <h1>Nouvel article</h1>
            <div class="form-group">
                <label for="name">Nom de l'article</label>
                <input type="text" name="name" id="name" class="form-control" required>
            </div>
            <br>
            <div class="form-group">
                
                <!--<input type="number" id="categoryId" name="categoryId" rows="3" class="form-control" required>-->
                <select  class="form-select" aria-label="select category" name="categoryId" id="categoryId" required>
                    <option value="">-- Choisir une catégorie --</option>
                    <?php foreach($categories as $category):?>
                        <option value="<?= $category->getId()?>"><?=$category->getName()?></option>
                    <?php endforeach ?>
                    
                </select>
            </div>
            <br>
            <div class="form-group">
                <label for="title">Titre de l'article</label>
                <input type="text" name="title" id="title" class="form-control" required>
            </div>
            <div class="form-group" >
                <label for="content">Contenu de l'article</label>
                <textarea id="content" name="content" rows="3" class="form-control"></textarea>
            </div>
            <br>
            <div class="text-center">
                <input type="submit" value="Ajouter article" class="btn btn-primary">
            </div>
        </form>
    </div>
<?php
}
?>